version: "3.8"

services:
  mongodb:
    image: mongo:6-jammy
    container_name: portfolio-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - portfolio-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - CLIENT_URL=http://localhost:8080
    depends_on:
      - mongodb
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - portfolio-network

volumes:
  mongodb_data:

networks:
  portfolio-network:
    driver: bridge
