apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ShelarAtharva404/portfolio-production.git'
    targetRevision: HEAD
    path: helm/portfolio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
